
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Willy
 */
public class Pizzas extends javax.swing.JFrame {
int nTipo=1;
int cantidad=1;
int tamannio=0;
int ingredientes=0;
  int TotalPagar=0;
     
    private String Totalpagar;
    public Pizzas() {
        initComponents();
        this.setLocationRelativeTo(null);
     SCANTIDAD.setValue(1);
     RBtradicional.setSelected(true);
     lblTotal.setText("$6");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipospizzas = new javax.swing.ButtonGroup();
        RBMilan = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SCANTIDAD = new javax.swing.JSpinner();
        Ctamannio = new javax.swing.JComboBox<>();
        jCheckAnchoas = new javax.swing.JCheckBox();
        jCheckMaiz = new javax.swing.JCheckBox();
        jCheckChampiñones = new javax.swing.JCheckBox();
        jCheckPiña = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        RBtradicional = new javax.swing.JRadioButton();
        RBHawaiana = new javax.swing.JRadioButton();
        TextNombre = new javax.swing.JTextField();
        Textdirec = new javax.swing.JTextField();
        Textelefono = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDirec = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BagregarC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipospizzas.add(RBMilan);
        RBMilan.setText("Milan");
        RBMilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMilanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setText("TIPO DE PIZZA");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("INGREDIENTES ADICIONALES");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("TAMAÑO");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("CANTIDAD");

        SCANTIDAD.setValue(1);
        SCANTIDAD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SCANTIDADStateChanged(evt);
            }
        });

        Ctamannio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEQUEÑA", "MEDIANA", "GRANDE" }));
        Ctamannio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtamannioActionPerformed(evt);
            }
        });

        jCheckAnchoas.setText("Anchoas");
        jCheckAnchoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckAnchoasActionPerformed(evt);
            }
        });

        jCheckMaiz.setText("Maiz");
        jCheckMaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMaizActionPerformed(evt);
            }
        });

        jCheckChampiñones.setText("Champiñones");
        jCheckChampiñones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckChampiñonesActionPerformed(evt);
            }
        });

        jCheckPiña.setText("Piña");

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setText("AÑADIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tipospizzas.add(RBtradicional);
        RBtradicional.setText("Tradicional");
        RBtradicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtradicionalActionPerformed(evt);
            }
        });

        tipospizzas.add(RBHawaiana);
        RBHawaiana.setText("Hawaiana");
        RBHawaiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBHawaianaActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblDirec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDirec.setText("Dirección");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefono.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel8.setText("DATOS DEL CLIENTE");

        BagregarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BagregarC.setText("AGREGAR");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/u.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDirec)
                            .addComponent(lblTelefono)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Textdirec, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Textelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel8)))
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(RBtradicional)
                            .addComponent(RBMilan))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ctamannio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RBHawaiana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckAnchoas)
                            .addComponent(jLabel2)
                            .addComponent(jCheckMaiz)
                            .addComponent(jCheckChampiñones)
                            .addComponent(jCheckPiña))
                        .addGap(172, 172, 172))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(BagregarC))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125)))
                .addGap(369, 369, 369))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Ctamannio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombre)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Textdirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDirec))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Textelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RBtradicional)
                                .addGap(8, 8, 8)
                                .addComponent(RBMilan)
                                .addGap(18, 18, 18)
                                .addComponent(RBHawaiana))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckAnchoas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BagregarC)
                            .addComponent(jCheckMaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jCheckChampiñones)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckPiña)
                            .addComponent(jButton1))
                        .addGap(39, 39, 39)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jCheckMaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMaizActionPerformed
        if(jCheckMaiz.isSelected()){
        ingredientes+=2;
        }
        else{
        ingredientes-=2;
        }
        TotalPagar();
    }//GEN-LAST:event_jCheckMaizActionPerformed

    private void jCheckChampiñonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckChampiñonesActionPerformed
        if(jCheckChampiñones.isSelected()){
        ingredientes+=3;
        }
        else{
        ingredientes-=3;
        }
        TotalPagar();
    }//GEN-LAST:event_jCheckChampiñonesActionPerformed
private void jCheckPiñaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        if(jCheckPiña.isSelected()){
        ingredientes+=1;
        }
        else{
        ingredientes-=1;
        }
        TotalPagar();
    }                               
    private void RBtradicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtradicionalActionPerformed
     nTipo=1;
     TotalPagar();
    }//GEN-LAST:event_RBtradicionalActionPerformed

    private void RBMilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMilanActionPerformed
       nTipo=2;
       TotalPagar();
    }//GEN-LAST:event_RBMilanActionPerformed

    private void RBHawaianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBHawaianaActionPerformed
       nTipo=3;
       TotalPagar();
    }//GEN-LAST:event_RBHawaianaActionPerformed

    private void SCANTIDADStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SCANTIDADStateChanged
    cantidad= Integer.parseInt(SCANTIDAD.getValue().toString());
     TotalPagar();   
    }//GEN-LAST:event_SCANTIDADStateChanged

    private void CtamannioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtamannioActionPerformed
        tamannio=Ctamannio.getSelectedIndex()+1;
         TotalPagar();
    }//GEN-LAST:event_CtamannioActionPerformed

    private void jCheckAnchoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckAnchoasActionPerformed
        if(jCheckAnchoas.isSelected()){
        ingredientes+=2;
        }
        else{
        ingredientes-=2;
        }
        TotalPagar();
    }//GEN-LAST:event_jCheckAnchoasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JOptionPane.showMessageDialog(this,"Total a pagar "+Totalpagar);
       SCANTIDAD.setValue(1);
       RBtradicional.setSelected(true);
       jCheckAnchoas.setSelected(false);
       jCheckChampiñones.setSelected(false);
       jCheckMaiz.setSelected(false);
       jCheckPiña.setSelected(false);
       Ctamannio.setSelectedIndex(0);
       lblTotal.setText("$ 10");
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void TotalPagar(){     
    switch (nTipo){
        case 1:
    TotalPagar=6+(tamannio*4);
    break;
        case 2:
         TotalPagar=11+(tamannio*4); 
         break;
         
        case 3:
             TotalPagar=13+(tamannio*4);
             
    
    }
    TotalPagar=(TotalPagar*cantidad+ingredientes);
    lblTotal.setText("$" +TotalPagar);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BagregarC;
    private javax.swing.JComboBox<String> Ctamannio;
    private javax.swing.JRadioButton RBHawaiana;
    private javax.swing.JRadioButton RBMilan;
    private javax.swing.JRadioButton RBtradicional;
    private javax.swing.JSpinner SCANTIDAD;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField Textdirec;
    private javax.swing.JTextField Textelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckAnchoas;
    private javax.swing.JCheckBox jCheckChampiñones;
    private javax.swing.JCheckBox jCheckMaiz;
    private javax.swing.JCheckBox jCheckPiña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDirec;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotal;
    public static javax.swing.ButtonGroup tipospizzas;
    // End of variables declaration//GEN-END:variables

   
}
